name: "CI"
on: [ "push", "pull_request" ]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: [ "windows-latest", "ubuntu-latest", "macOS-latest" ]
        go: [ "1.25.x" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: text-adi/build-language-i18n-action@v1
        env:
          DIR: i18n/locales/

      - uses: WillAbides/setup-go-faster@v1.15.0
        with:
          go-version: ${{ matrix.go }}
      - run: "go vet ./..."
      - run: "go test -v ./..."
      - uses: dominikh/staticcheck-action@v1.4.1
        with:
          version: "2025.2"
          install-go: false
          cache-key: ${{ matrix.go }}